Repository onflow/cadence-tools, pull requests merged in 2022-09, with the labels that each got.

#19 Delete outdated analyzer installation scripts
  lint/README.md
  lint/cadence-analyzer-version.txt
  lint/install-cadence-analyzer.ps1
  lint/install-cadence-analyzer.sh
Labels: Improvement

#22 Add npm packages for language-server and docgen tools
  npm-packages/cadence-docgen/.gitignore
  npm-packages/cadence-docgen/README.md
  npm-packages/cadence-docgen/jest.config.js
  npm-packages/cadence-docgen/package-lock.json
  npm-packages/cadence-docgen/package.json
  npm-packages/cadence-docgen/src/go.js
  npm-packages/cadence-docgen/src/index.ts
  npm-packages/cadence-docgen/tests/index.test.ts
  npm-packages/cadence-docgen/tests/setup.js
  npm-packages/cadence-docgen/tsconfig.json
  npm-packages/cadence-language-server-demo/.gitignore
  npm-packages/cadence-language-server-demo/README.md
  npm-packages/cadence-language-server-demo/package-lock.json
  npm-packages/cadence-language-server-demo/package.json
  npm-packages/cadence-language-server-demo/src/cadence.ts
  npm-packages/cadence-language-server-demo/src/index.html
  npm-packages/cadence-language-server-demo/src/index.ts
  npm-packages/cadence-language-server-demo/tsconfig.json
  npm-packages/cadence-language-server-demo/webpack.config.js
  npm-packages/cadence-language-server/.gitignore
  npm-packages/cadence-language-server/README.md
  npm-packages/cadence-language-server/jest.config.js
  npm-packages/cadence-language-server/package-lock.json
  npm-packages/cadence-language-server/package.json
  npm-packages/cadence-language-server/src/go.js
  npm-packages/cadence-language-server/src/index.ts
  npm-packages/cadence-language-server/tests/index.test.ts
  npm-packages/cadence-language-server/tests/setup.js
  npm-packages/cadence-language-server/tsconfig.json
Labels: Chore

#20 [lint] Update to Cadence v0.26.1 and Go 1.19
  .github/workflows/ci.yml
  lint/analyzers/analyzers_test.go
  lint/go.mod
  lint/go.sum
  lint/main.go
Labels: Improvement

#25 Update test to Cadence v0.27.0
  test/go.mod
  test/go.sum
  test/test_framework_test.go
  test/test_runner.go
Labels: Improvement

#23 Update lint to Cadence v0.27.0
  lint/analyzers/analyzers_test.go
  lint/analyzers/number_function_argument_analyzer.go
  lint/analyzers/redundant_cast_analyzer.go
  lint/analyzers/reference_operator_analyzer.go
  lint/go.mod
  lint/go.sum
  lint/main.go
Labels: Improvement

#24 Update docgen to Cadence v0.27.0
  docgen/doc_generator.go
  docgen/go.mod
  docgen/go.sum
  docgen/test/doc_gen_test.go
Labels: Improvement

#27 Update LS to Cadence v0.27.0
  CONTRIBUTING.md
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/contracts_test.go
  languageserver/integration/entrypoint_test.go
  languageserver/server/server.go
Labels: Improvement

#28 [lint] Add silent and color flags
  lint/main.go
Labels: Feature

#29 [lint] Refactor so it can be embedded
  lint/README.md
  lint/analyzer.go
  lint/analyzers_test.go
  lint/cmd/lint/flag.go
  lint/cmd/lint/main.go
  lint/deprecated_key_functions_analyzer.go
  lint/deprecated_key_functions_analyzer_test.go
  lint/error.go
  lint/go.mod
  lint/go.sum
  lint/lint.go
  lint/number_function_argument_analyzer.go
  lint/number_function_argument_analyzer_test.go
  lint/redundant_cast_analyzer.go
  lint/redundant_cast_analyzer_test.go
  lint/reference_operator_analyzer.go
  lint/reference_operator_analyzer_test.go
  lint/unnecessary_force_analyzer.go
  lint/unnecessary_force_analyzer_test.go
Labels: Improvement
