Repository onflow/cadence-tools, pull requests merged in 2023-06, with the labels that each got.

#130 Update test to Cadence v0.39.1
  test/emulator_backend.go
  test/go.mod
  test/go.sum
  test/test_framework_test.go
  test/test_runner.go
Labels: Improvement

#114 Retrieve `Blockchain` logs
  test/emulator_backend.go
  test/go.mod
  test/test_framework_test.go
  test/test_runner.go
Labels: Feature

#135 Fix AuthAccount analyzer
  lint/auth_account_parameter_analyzer.go
  lint/auth_account_parameter_analyzer_test.go
Labels: bugfix

#134 Update LS to Cadence v0.39.2
  languageserver/go.mod
  languageserver/go.sum
  languageserver/server/server.go
  languageserver/server/stdlib.go
  languageserver/test/index.test.ts
Labels: Improvement

#137 Enable capability controllers
  languageserver/server/server.go
Labels: Feature

#141 [test] Update to Cadence v0.39.4
  test/go.mod
  test/go.sum
Labels: Improvement

#142 [lint] Update to Cadence v0.39.4
  lint/go.mod
  lint/go.sum
Labels: Improvement

#143 [LS] Update to Cadence v0.39.4
  languageserver/go.mod
  languageserver/go.sum
Labels: Improvement

#138 Add support for retrieving `stdlib` events
  test/emulator_backend.go
  test/test_framework_test.go
  test/test_runner.go
Labels: Feature

#146 update reference to cadence to use newest version
  languageserver/go.mod
  languageserver/go.sum
Labels: Language Server

#140 [LS] Add test for Cadence features behind feature flags
  languageserver/test/index.test.ts
Labels: Improvement

#151 Fix error when returning empty `Array` & `Dictionary` values from scripts
  test/emulator_backend.go
  test/test_framework_test.go
Labels: bugfix

#152 Update to Cadence v0.39.12
  test/emulator_backend.go
  test/go.mod
  test/go.sum
  test/test_framework_test.go
Labels: Improvement

#154 [lint] Update to Cadence v0.39.12
  lint/go.mod
  lint/go.sum
Labels: Improvement

#145 [lint] Generalize deprecated key functions analyzer to deprecated member analyzer
  lint/analyzer.go
  lint/deprecated_key_functions_analyzer.go
  lint/deprecated_key_functions_analyzer_test.go
  lint/deprecated_member_analyzer.go
  lint/deprecated_member_analyzer_test.go
Labels: Feature

#147 [LS] Mark members as deprecated through diagnostics and in completion items
  languageserver/server/server.go
Labels: Feature

#156 [LS] Update to Cadence v0.39.12
  languageserver/go.mod
  languageserver/go.sum
  languageserver/server/server.go
Labels: Improvement

#160 [test] Fix import replacement for new import format
  test/emulator_backend.go
  test/test_framework_test.go
Labels: bugfix
