Repository onflow/cadence-tools, pull requests merged in 2023-10, with the labels that each got.

#218 [LS] Implement `ReadRandom` for standardLibrary type
  languageserver/server/stdlib.go
Labels: Improvement

#210 [test] Unify backend environment for Unit & Integration tests
  test/blockchain_helpers.cdc
  test/emulator_backend.go
  test/go.mod
  test/go.sum
  test/test_framework_provider.go
  test/test_framework_test.go
  test/test_runner.go
Labels: Improvement

#227 [lint] Update to Cadence v0.42.1
  lint/go.mod
  lint/go.sum
Labels: Improvement

#228 [LS] Add string import resolver to WASM LS
  languageserver/cmd/languageserver/main_wasm.go
Labels: Feature, Language Server

#224 [LS] Allow importing any flow.json contracts using new import syntax
  languageserver/integration/flow.go
  languageserver/test/a.cdc
  languageserver/test/flow.json
  languageserver/test/index.test.ts
Labels: Language Server, bugfix

#230 Remove Code-QL Scanner
  .github/workflows/code-vulnerability-analysis.yml
Labels: Chore
