Repository onflow/cadence-tools, pull requests merged in 2023-11, with the labels that each got.

#234 [test] Increase the number of predefined accounts to 20
  test/emulator_backend.go
Labels: Improvement

#231 [LS] Enable new import syntax resolution without emulator connection
  languageserver/integration/commands.go
  languageserver/integration/commands_test.go
  languageserver/integration/flow.go
  languageserver/integration/integration.go
  languageserver/integration/mock_flow_test.go
  languageserver/integration/mock_state_test.go
  languageserver/integration/resolvers.go
  languageserver/integration/resolvers_test.go
  languageserver/integration/state.go
Labels: Language Server, bugfix

#236 [lint] Bump Flow dependencies
  lint/go.mod
  lint/go.sum
Labels: Improvement

#237 [test] Bump Flow dependencies
  test/blockchain_helpers.go
  test/emulator_backend.go
  test/go.mod
  test/go.sum
  test/test_framework_test.go
Labels: Improvement

#240 Improve CI: Only run job for project if files changed
  .github/workflows/ci.yml
Labels: Chore

#241 [LS] Update to Cadence v0.42.5
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/flow.go
  languageserver/server/server.go
  languageserver/server/stdlib.go
Labels: Improvement

#243 [LS] Fix wasm target
  languageserver/cmd/languageserver/main_wasm.go
  languageserver/go.mod
  languageserver/go.sum
  languageserver/server/server.go
Labels: bugfix

#244 [LS] Ensure the LS binaries (native and wasm) can be built
  .github/workflows/ci.yml
  languageserver/Makefile
Labels: Chore

#246 [test] Test framework bug fixes
  test/helpers/blockchain_helpers.go
  test/helpers/blockchain_helpers_test.go
  test/test_framework_test.go
  test/test_runner.go
Labels: Improvement, bugfix

#251 [test] Update flow emulator
  test/dummy_test.go
  test/go.mod
  test/go.sum
Labels: Improvement
