Repository onflow/cadence-tools, pull requests merged in 2023-09, with the labels that each got.

#196 [test] Allow setting blockchain's clock
  test/emulator_backend.go
  test/go.mod
  test/go.sum
  test/test_framework_test.go
Labels: Feature

#206 [test] Allow `TestRunner` to execute test cases randomly
  test/test_framework_test.go
  test/test_runner.go
Labels: Feature

#205 [test] Clean state for each emulator backend instance
  test/emulator_backend.go
  test/go.mod
  test/go.sum
  test/test_framework_provider.go
  test/test_framework_test.go
  test/test_runner.go
Labels: Improvement

#207 [test] Add blockchain snapshots
  test/emulator_backend.go
  test/go.mod
  test/go.sum
  test/test_framework_test.go
Labels: Feature

#197 [test] Allow test scripts to import types from deployed contracts
  test/emulator_backend.go
  test/test_framework_test.go
  test/test_runner.go
Labels: Feature

#211 Update to latest stable cadence
  .github/release.yml
  languageserver/conversion/conversion.go
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/entrypoint_test.go
  languageserver/server/server.go
  languageserver/server/stdlib.go
  languageserver/test/index.test.ts
  languageserver/test/transaction-multiple.cdc
  languageserver/test/transaction.cdc
  lint/auth_account_parameter_analyzer_test.go
  lint/deprecated_member_analyzer.go
  lint/go.mod
  lint/go.sum
  test/blockchain_helpers.cdc
  test/blockchain_helpers.go
  test/emulator_backend.go
  test/go.mod
  test/go.sum
  test/scripts.go
  test/scripts/get_current_block_height.cdc
  test/scripts/get_flow_balance.cdc
  test/test_framework_provider.go
  test/test_framework_test.go
  test/test_runner.go
  test/transactions.go
  test/transactions/burn_flow.cdc
  test/transactions/mint_flow.cdc
Labels: Improvement

#199 Run CI separately for each sub-module
  .github/workflows/ci.yml
  Makefile
Labels: Chore

#213 Improve issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: Chore
