Repository onflow/cadence-tools, pull requests merged in 2023-08, with the labels that each got.

#180 [test] Update test scripts with the latest API additions
  test/test_framework_test.go
Labels: Improvement

#158 [LS] Ensure LS exit, even if test fails
  languageserver/test/index.test.ts
Labels: bugfix

#183 [LS] Update release process
  languageserver/README.md
Labels: Documentation

#185 [NPM] Release instructions for LS
  npm-packages/cadence-language-server/README.md
Labels: Documentation

#186 [lint] Auto update to onflow/cadence v0.40.0
  lint/go.mod
  lint/go.sum
Labels: Improvement

#188 [test] Update to Cadence v0.40.0
  test/go.mod
  test/go.sum
Labels: Improvement

#190 [lint] Fix Go SDK
  lint/go.mod
  lint/go.sum
Labels: Chore

#189 [LS] Update to Cadence v0.40.0
  languageserver/go.mod
  languageserver/go.sum
  languageserver/test/index.test.ts
Labels: Improvement

#161 [LS] Provide code actions for suggested fixes of sema errors
  languageserver/conversion/conversion.go
  languageserver/server/server.go
Labels: Feature

#162 [LS] Combine code actions, support optional chaining suggestion
  languageserver/server/server.go
Labels: Improvement

#181 [test] Cadence testing framework improvements
  test/blockchain_helpers.cdc
  test/blockchain_helpers.go
  test/emulator_backend.go
  test/scripts.go
  test/scripts/get_current_block_height.cdc
  test/scripts/get_flow_balance.cdc
  test/test_framework_test.go
  test/test_runner.go
  test/transactions.go
  test/transactions/burn_flow.cdc
  test/transactions/mint_flow.cdc
Labels: Feature

#187 [LS] Add checker support for `BlockchainHelpers` identifier location
  languageserver/go.mod
  languageserver/go.sum
  languageserver/server/server.go
Labels: Feature

#195 [test] Add assertions to verify loading of standard library flow events
  test/test_framework_test.go
Labels: Improvement

#198 Update to latest stable cadence version
  .github/workflows/ci.yml
  Makefile
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/contracts_test.go
  languageserver/integration/entrypoint_test.go
  languageserver/server/document_test.go
  languageserver/server/linting_test.go
  languageserver/server/server.go
  languageserver/server/stdlib.go
  languageserver/test/bar.cdc
  languageserver/test/foo.cdc
  languageserver/test/index.test.ts
  languageserver/test/script.cdc
  languageserver/test/zoo.cdc
  lint/README.md
  lint/auth_account_parameter_analyzer_test.go
  lint/deprecated_member_analyzer.go
  lint/deprecated_member_analyzer_test.go
  lint/go.mod
  lint/go.sum
  lint/number_function_argument_analyzer_test.go
  lint/redundant_cast_analyzer_test.go
  lint/reference_operator_analyzer.go
  lint/reference_operator_analyzer_test.go
  lint/unnecessary_force_analyzer_test.go
  npm-packages/cadence-language-server-demo/src/index.ts
  test/go.mod
  test/go.sum
  test/test_framework_test.go
Labels: Chore

#200 [lint] Update cadence version to v0.41.0-stable-cadence.1
  lint/go.mod
  lint/go.sum
Labels: Chore

#201 [test] Update cadence version to v0.41.0-stable-cadence.1
  test/go.mod
  test/go.sum
Labels: Chore

#202 [languageserver] Update cadence version to v0.41.0-stable-cadence.1
  languageserver/go.mod
  languageserver/go.sum
Labels: Chore
