Repository onflow/cadence-tools, pull requests merged in 2023-05, with the labels that each got.

#111 [LS] Fix import failure of `Test` contract
  languageserver/server/server.go
Labels: Improvement

#115 Fix inlay hints: add type annotation for resource types
  languageserver/server/server.go
Labels: bugfix

#118 Enable attachments and account linking
  languageserver/integration/commands_test.go
  languageserver/server/server.go
Labels: Feature

#119 Allow insertion of inlay hints
  languageserver/integration/entrypoint.go
  languageserver/protocol/documentchanges.go
  languageserver/protocol/json.go
  languageserver/protocol/types.go
  languageserver/scripts/.gitignore
  languageserver/scripts/README.md
  languageserver/scripts/package-lock.json
  languageserver/scripts/package.json
  languageserver/scripts/tsconfig.json
  languageserver/server/server.go
Labels: Feature

#128 Add `EmulatorBackend.Reset` method and `beforeEach` / `afterEach` hooks
  test/emulator_backend.go
  test/test_framework_test.go
  test/test_runner.go
Labels: Feature

#127 Fix unnamed import symbols
  languageserver/conversion/conversion.go
  languageserver/server/server.go
Labels: Feature

#124 Deploy common contracts on `EmulatorBackend`'s `Blockchain`
  test/emulator_backend.go
  test/go.mod
  test/go.sum
  test/test_framework_test.go
Labels: Improvement
