Repository onflow/cadence-tools, pull requests merged in 2023-12, with the labels that each got.

#226 [test] Fix storage errors for unit testing
  test/go.mod
  test/test_framework_test.go
  test/test_runner.go
Labels: bugfix

#256 [test] Update to latest flow-go
  test/emulator_backend.go
  test/go.mod
  test/go.sum
Labels: Chore

#258 [lint] Update to Cadence 1.0 RC1
  lint/auth_account_parameter_analyzer.go
  lint/auth_account_parameter_analyzer_test.go
  lint/deprecated_member_analyzer.go
  lint/deprecated_member_analyzer_test.go
  lint/go.mod
  lint/go.sum
  lint/number_function_argument_analyzer_test.go
  lint/redundant_cast_analyzer_test.go
  lint/reference_operator_analyzer.go
  lint/reference_operator_analyzer_test.go
  lint/unnecessary_force_analyzer_test.go
Labels: Improvement

#259 [test] Update to Cadence 0ff20e15e7e1
  .github/workflows/ci.yml
  lint/README.md
  lint/go.mod
  test/emulator_backend.go
  test/go.mod
  test/go.sum
  test/helpers/blockchain_helpers.cdc
  test/scripts/get_current_block_height.cdc
  test/scripts/get_flow_balance.cdc
  test/test_framework_provider.go
  test/test_framework_test.go
  test/test_runner.go
  test/transactions/burn_flow.cdc
  test/transactions/mint_flow.cdc
Labels: Improvement

#260 [LS] Update to Cadence 1.0 RC1
  languageserver/Makefile
  languageserver/conversion/conversion.go
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/contracts_test.go
  languageserver/integration/entrypoint_test.go
  languageserver/integration/resolvers_test.go
  languageserver/server/linting_test.go
  languageserver/server/server.go
  languageserver/server/stdlib.go
  languageserver/test/a.cdc
  languageserver/test/bar.cdc
  languageserver/test/foo.cdc
  languageserver/test/index.test.ts
  languageserver/test/script.cdc
  languageserver/test/transaction-multiple.cdc
  languageserver/test/transaction.cdc
  languageserver/test/zoo.cdc
  npm-packages/cadence-language-server/package-lock.json
Labels: Improvement

#266 Always require signer argument when signing a transaction with the se…
  test/emulator_backend.go
  test/test_framework_test.go
Labels: Improvement

#262 [test] Add some test assertions for `RandomBeaconHistory`'s usage
  test/test_framework_test.go
Labels: Improvement
