Repository onflow/cadence-tools, pull requests merged in 2023-01, with the labels that each got.

#48 [LS] Using local emulator
  languageserver/integration/flow.go
Labels: Language Server, Improvement

#53 Update lint to cadence v0.31.0
  lint/go.mod
  lint/go.sum
Labels: Improvement

#54 Update languageserver to cadence v0.31.0
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/entrypoint_test.go
Labels: Improvement

#56 [LS] Strip extra slash on windows paths
  languageserver/integration/commands.go
Labels: Bugfix, Language Server

#60 [LS] Bugfix clean Windows paths in resolvers
  languageserver/integration/commands.go
  languageserver/integration/flow.go
  languageserver/integration/integration.go
  languageserver/integration/mock_flow_test.go
  languageserver/integration/resolvers.go
Labels: Bugfix, Language Server, DSS

#63 [LS] Augmented checker configuration for scripts
  languageserver/server/server.go
  languageserver/server/stdlib.go
  languageserver/test/index.test.ts
Labels: Bugfix, Language Server

#70 [LS] Refactor creation of config
  languageserver/server/server.go
  languageserver/server/stdlib.go
Labels: Improvement, DSS

#69 [LS] Implement account access check
  languageserver/integration/flow.go
  languageserver/integration/integration.go
  languageserver/integration/mock_flow_test.go
  languageserver/integration/resolvers.go
  languageserver/server/server.go
Labels: Feature

#52 [LS] Support new import syntax
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/flow.go
  languageserver/integration/resolvers.go
  languageserver/server/server.go
  languageserver/test/bar.cdc
  languageserver/test/flow.json
  languageserver/test/index.test.ts
  languageserver/test/package-lock.json
  languageserver/test/zoo.cdc
Labels: Language Server, Improvement

#72 [LS] Flow client flag consistent with CLI
  languageserver/cmd/languageserver/main.go
  languageserver/go.mod
  languageserver/run.sh
  languageserver/test/index.test.ts
Labels: Improvement

#73 [LS] Don't force showing messages
  languageserver/server/server.go
Labels: Improvement

#74 [LS] String import resolver
  languageserver/integration/flow.go
  languageserver/integration/integration.go
  languageserver/integration/mock_flow_test.go
  languageserver/integration/resolvers.go
  languageserver/integration/resolvers_test.go
  languageserver/server/location.go
  languageserver/test/index.test.ts
Labels: Bugfix
