Repository onflow/cadence-tools, pull requests merged in 2024-01, with the labels that each got.

#267 [Test] Add WithLogger to TestRunner and default to zerolog.Nop()
  test/emulator_backend.go
  test/test_framework_provider.go
  test/test_framework_test.go
  test/test_runner.go
Labels: Feature

#270 [Test] Merge pull request #267 from onflow/jribbink/add-logger (test/v0.14)
  test/emulator_backend.go
  test/test_framework_provider.go
  test/test_framework_test.go
  test/test_runner.go
Labels: Feature

#272 [test] Use filenames instead of script ID when printing test results
  test/test_framework_test.go
  test/test_runner.go
Labels: Improvement

#273 [LS] Update flowkit to latest version on v0.33 branch
  languageserver/go.mod
  languageserver/go.sum
Labels: Language Server, Improvement

#276 Auto update to onflow/cadence v1.0.0-M4
  lint/deprecated_member_analyzer.go
  lint/go.mod
  lint/go.sum
  lint/number_function_argument_analyzer.go
  lint/redundant_cast_analyzer.go
  lint/unnecessary_force_analyzer.go
Labels: Chore

#277 [test] Update to Cadence v1.0.0-M4
  test/go.mod
  test/go.sum
  test/test_framework_test.go
  test/transactions/burn_flow.cdc
  test/transactions/mint_flow.cdc
Labels: Chore

#278 [LS] Update to Cadence v1.0.0-M4
  languageserver/go.mod
  languageserver/go.sum
  languageserver/server/server.go
Labels: Chore
