Repository onflow/cadence-tools, pull requests merged in 2024-02, with the labels that each got.

#281 [DG] Fix how to run path
  docgen/README.md
Labels: Documentation

#283 [LS] Update to Cadence v1.0.0-M7 and new github.com/onflow/flowkit/v2
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/commands.go
  languageserver/integration/commands_test.go
  languageserver/integration/diagnostics.go
  languageserver/integration/flow.go
  languageserver/integration/integration.go
  languageserver/integration/mock_state_test.go
  languageserver/integration/resolvers.go
  languageserver/integration/resolvers_test.go
  languageserver/integration/state.go
  languageserver/protocol/json.go
Labels: Improvement

#285 [lint] Add Cadence 1.0 analyzer with basic linting rules
  lint/analyzer.go
  lint/analyzers_test.go
  lint/cadence_v1_analyzer.go
  lint/cadence_v1_analyzer_test.go
  lint/diagnostic.go
Labels: Feature

#294 [lint] Check for nil pointers in CadenceV1Analyzer type annotation inspection
  lint/cadence_v1_analyzer.go
  lint/cadence_v1_analyzer_test.go
Labels: bugfix

#286 [LS] Add support for new analysis.Diagnostic information & CadenceV1Analyzer
  languageserver/server/server.go
Labels: Improvement
